### ISSUE TITLE
GWT Megamenu

### ISSUE THREAD

**Issue by htupasjr** [iGovPhil/gwt-drupal#12]
Good day!

Would just like to ask how to install the mega-menu. I was assuming that there will be a feature embedded on the theme settings since there is a note in the README file that the mega-menu was fixed. 

Thank you so much.

**Comment by v0j** [comment]
EDIT: there was one time that mega menu was considered to be added as a default feature in the template (Drupal, Wordpress, Joomla) but since there's a lot of complications making it harder to implement/followed by the users we then removed the feature all together.

Unfortunately, we will no longer support the mega-menu in the newer version. There might be traces of mega-menu, in fact we haven't removed it totally. We just simply disabled the codes from showing up.

However, we strongly advice to avoid using the mega-menu to avoid future incompatibilities.
